# Generated by Django 3.0.2 on 2020-02-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型名字')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('date', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('description', models.TextField(verbose_name='文章描述')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
                ('type', models.ManyToManyField(to='app01.Type')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
