# Generated by Django 3.0.2 on 2020-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[(0, '女'), (1, '男')], default=1, max_length=32, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='作者姓名'),
            preserve_default=False,
        ),
    ]
