# Generated by Django 3.0.2 on 2020-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200217_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章合集'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '作者名单'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': '类型'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='gender',
        ),
        migrations.AddField(
            model_name='author',
            name='gender1',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
