# Generated by Django 2.2.1 on 2020-02-19 11:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200219_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommend',
            field=models.IntegerField(default=1, verbose_name='图文推荐'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='描述'),
        ),
    ]
