# Generated by Django 2.2.1 on 2020-02-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200219_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click',
            field=models.IntegerField(default=1, verbose_name='点击率'),
            preserve_default=False,
        ),
    ]
